### ISSUE TITLE
pam`s seed for Forectery Seed Oil. (look for possibility)

### ISSUE THREAD

**Issue by demethan** [BreakfastCraft/BreakfastBuffet#16]
would be nice if pam`s stuff was compatible with seed oil .

Maybe there is a script out there that does that or its an easy config change. 

thanks for looking.

**Comment by lunchington** [comment]
Which ones? I can add recipes for the Squeezer(I think?)

**Comment by pawlywog** [comment]
you can just do the interchangeable ones. from what I can tell its 

almond
banana
cashew
chestnut
coconut
cinnamon
date
fig
grapefruit
lemon
lime
maple
mango
nutmeg
olive
orange
papaya
peach
pear
pecan
plum
starfruit

which is almost all of them but idk if they all give seed oil. i know binnie added liquor into the game so i imagine some of those are for juice.. but the nuts should be squeezable

**Comment by lunchington** [comment]
Squeezer has a FFILTERED INPUT not allowing things to be added even with minetweaker.

An addition was made to the code yesterday that will fix this. Once it is released I will add the recipes.

https://github.com/Voidi/ModTweaker2/commit/0cc7032a0d9a9d4dfe45f3a2b31e54b4678c2760

**Comment by lunchington** [comment]
Compiled most recent source from thier github, it allows custom recipes for forestry machines. CONFIRMED IN SSP.

**Comment by lunchington** [comment]
CLOSING issue as it is effectivly solved.
