### ISSUE TITLE
Crystal scribing tools from Forbidden Magic are not craftable

### ISSUE THREAD

**Issue by F4ndroid** [BreakfastCraft/BreakfastBuffet#19]
No vis cost is listed in NEI or the Thaumonomicon. When I put everything in place in the arcane workbench it says "insufficient vis" and doesn't display a cost. I've tried with different shards and different types of dye, even the shadow ink from Forbidden Magic, no dice.

**Comment by topher2010** [comment]
There is an update to Forbidden Magic that fixes this.  It will be put in the next update.
