### ISSUE TITLE
Vanilla potions not in NEI

### ISSUE THREAD

**Issue by acu2005** [BreakfastCraft/BreakfastBuffet#2]
Vanillla potions are missing from the recipe list in NEI on Breakfast Buffet, possible conflict with INPureCOre.

**Comment by slidingmike** [comment]
I don't believe there is a solution to this.

**Comment by topher2010** [comment]
Still need to research if there's a solution or not, but it doesn't look promising to me

**Comment by slidingmike** [comment]
http://forum.feed-the-beast.com/threads/1-0-2-1-0-2-vanilla-potions-not-in-nei.57222/

This might be what we're looking for.

**Comment by topher2010** [comment]
Fixed in BB2.0
