### ISSUE TITLE
Problem with Unstable Ingots

### ISSUE THREAD

**Issue by F4ndroid** [BreakfastCraft/BreakfastBuffet#21]
When crafted, unstable ingots cannot be crafted into angel rings. I figured I'd just salvage what I could and let it kill me. The ingots didn't actually explode, but went into my gravestone after killing me. When I broke my grave it instantly killed me again. This happened a few times until I figured I'd break the grave from far enough away to not pick anything up, then gradually picked up my stuff without picking up the ingots. But the ingots never actually went away; they just floated there. I hopped into singleplayer to test it and went into creative, then crafted the ingots. I placed all the stuff in the appropriate spots in the crafting grid and it wouldn't craft. I put the ingots in my inventory and exited the crafting interface, which then caused a constant series of explosions until I deleted the ingots.
Upon checking the configs and Minetweaker scripts, I've determined that the recipe is supposed to work.

I checked Tema's GitHub and there is an issue with the current version. Shift-clicking to craft produces this issue, so my advice is to either update when a fix is available or downgrade to the previous build. In the meantime you can craft them by clicking them one-by-one to craft.

**Comment by lunchington** [comment]
I thought making them "by hand" was the intended mechanic.  The issue starts saying they cannot be crafted then they can just not in an "easy" mechanic breaking way . Is this what I am understanding? 

I see no issue.

We will not be downgrading to facilitate making creative flight even easier than it is. It is counter to the point of the pack. We will be pushing an upgrade this weekend, If the ""fix"" is in his update so be it.

Again I do not see this as an issue.

**Comment by demethan** [comment]
Don't shift click the unstable ingots
