### ISSUE TITLE
Crashing on log in 

### ISSUE THREAD

**Issue by nunley21** [BreakfastCraft/BreakfastBuffet#22]
I crash on login her is my log 
http://pastebin.com/3t7VhA22

**Comment by lunchington** [comment]
This error is directly related to the setting in enderio.cfg inside you INSTANCE/config/enderio directory. the B:Misc=true should be replaced with false.

EXAMPLE:

    replacewitherskeletons {
         # Separates wither and normal skeletons into different entities, enables the powered spawner to treat them differently [EXPERIMENTAL - MAY CAUSE ISSUES WITH OTHER MODS]
         B:Misc=true
    }

SHOULD BE

    replacewitherskeletons {
         # Separates wither and normal skeletons into different entities, enables the powered spawner to treat them differently [EXPERIMENTAL - MAY CAUSE ISSUES WITH OTHER MODS]
         B:Misc=false
    }

**Comment by topher2010** [comment]
Option changed in BB2.1
