### ISSUE TITLE
Un restrict the MFR Chunk loaders

### ISSUE THREAD

**Issue by demethan** [BreakfastCraft/BreakfastBuffet#29]
If you can supply them with power and mob juice, you should be allowed the size you want.

Radius of 2 is horrible. it is not a world anchor. 

radius of 5 would be fine. 

Thanks.

**Comment by topher2010** [comment]
Still am unable to find a config for this.  Any luck on your end?

**Comment by demethan** [comment]
powercrystals/minefactoryreloaded/common.cfg

# If true, the Chunk Loader will ignore forgeChunkLoading.cfg.
B:IgnoreChunkLimit=false

**Comment by topher2010** [comment]
Will be so in the next update
