### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Xenosaga20** [BreakfastCraft/BreakfastBuffet#3]
Mod suggestion possibly redpower 2 the mod with the micro blocks and pneumatic pipes always loved that mod

**Comment by topher2010** [comment]
Redpower 2 is a dead mod, Eloraam doesn't update shit, lol.  What mod with microblocks, and pneumatic pipes?  Do you mean the Tubes! mod?

**Comment by topher2010** [comment]
Looking into the Tubes! mod, redpower 2 isn't updated, and microblocks are already in.
