### ISSUE TITLE
RFTools syringe recipes

### ISSUE THREAD

**Issue by F4ndroid** [BreakfastCraft/BreakfastBuffet#30]
Crafting anything from RFTools that uses a syringe always results in the default value for the syringe being applied to the recipe. For example, if you stab a zomble with a syringe and try to craft a saturation module with it it will make a feather falling module instead.

See https://github.com/McJty/RFTools/issues/91

**Comment by topher2010** [comment]
We'll have to keep an eye on updates, as this doesn't appear to be solved in any of the mods involved at this time.

**Comment by topher2010** [comment]
Can you see if this is still an issue?

**Comment by F4ndroid** [comment]
This is still an issue. I suggest we add an alternative recipe through MineTweaker.

**Comment by TomeWyrm** [comment]
This has been fixed!

Apparently it had to do with Forge enforcing the ore dictionary triggering an odd interaction with "a fairly late OreDict.initVanillaEntries which triggers the recipe replacement".

V7b of DragonAPI fixes the issue with Reika's mods. It also affected a few other NBT-sensitive crafting recipes. Update Reika's mods and you won't have to minetweak anything!

**Comment by F4ndroid** [comment]
Fixed in 3.0.1.
