### ISSUE TITLE
Config change

### ISSUE THREAD

**Issue by F4ndroid** [BreakfastCraft/BreakfastBuffet#31]
$minecraft/configs/IguanaTinkerTweaks/main.cfg

randombonuses {
    B:allowAttack=true
    B:allowAutosmelt=false
    B:allowBaneOfArthropods=false
    B:allowBeheading=true
    B:allowCritical=true
    B:allowDiamond=true
    B:allowEmerald=true
    B:allowFiery=true   <----Change this to false. It keeps ruining the Ender Ender scythe.
    B:allowJagged=true
    B:allowKnockback=true
    B:allowLifeSteal=true
    B:allowLuckLooting=true
    B:allowRedstone=true
    B:allowReinforced=true
    B:allowRepair=true
    B:allowSilkTouch=true
    B:allowSmite=true
    B:allowStonebound=false
}

**Comment by demethan** [comment]
Noted.

**Comment by topher2010** [comment]
Done, will be in the next Dev update, already changed on Dev server.
