### ISSUE TITLE
Potion ID conflict

### ISSUE THREAD

**Issue by F4ndroid** [BreakfastCraft/BreakfastBuffet#32]
The ID used for the transfix ability from Witchery conflicts with the freeze potion ID from RotaryCraft. I suggest moving the freeze potion ID to something higher to resolve the conflict.

It's in minecraft/config/Reika/RotaryCraft.cfg and the line is:
"other ids" {
    I:"Freeze Potion ID"=35
}

**Comment by F4ndroid** [comment]
I fixed the issue.
Change this line in Witchery.cfg from:
    I:"witchery:potion.paralysed"=32
to:
    I:"witchery:potion.paralysed"=116

Changes must be client- and server-side.

**Comment by demethan** [comment]
Thx Fan

**Comment by topher2010** [comment]
This has been changed and will be included in the next dev update.  Changed on the Dev server.
