### ISSUE TITLE
Bug with block breaker from OpenBlocks

### ISSUE THREAD

**Issue by F4ndroid** [BreakfastCraft/BreakfastBuffet#33]
Disable the block breaker due to a dupe glitch.

**Comment by demethan** [comment]
What does it dupe?

**Comment by F4ndroid** [comment]
Any block with a mining level below cobalt.

**Comment by topher2010** [comment]
F4ndroid, can you verify if this remains an issue?

**Comment by F4ndroid** [comment]
Issue has been fixed with the mod updates.
