### ISSUE TITLE
Random Things client/server config mismatch

### ISSUE THREAD

**Issue by F4ndroid** [BreakfastCraft/BreakfastBuffet#35]
# Whether players are NOT allowed to sleep during a bloodmoon
    B:BloodMoonNoSleep=true <--- Should be set to false on the client, as the server is set to false.

Currently, the mismatch causes players who attempt to sleep during blood moons to get an error message ("You don't feel tired right now") and continue to move around and play as normal. Serverside the player is sleeping as normal.

Minor annoyance at most, so low-priority.

**Comment by topher2010** [comment]
Will be corrected in BB3.0.1
