### ISSUE TITLE
Fixes for TiCon issues

### ISSUE THREAD

**Issue by F4ndroid** [BreakfastCraft/BreakfastBuffet#37]
In $config/IguanaTinkerTweaks/modules.cfg:
 
   # Adds additional MobHeads and control over MobHead drops.
    B:MobHeads=false

This was set to true. This setting gives control of mob heads back to Minecraft. This will stop endermen from dropping two heads on death (one from IguanaTweaks, one from Ender IO) and let autonomous activator wither skeleton farms function again.

    # Various Tweaks for vanilla Minecraft and Tinker's Construct. See Config.
    B:Restrictions=false

This was also set to true. This is to fix the issue with slime crystals not crafting tough rods/bindings.

**Comment by topher2010** [comment]
Done.  will be in BB3.0.1
