### ISSUE TITLE
EnderIO Farming Stations and Magical Crops

### ISSUE THREAD

**Issue by adam4826** [BreakfastCraft/BreakfastBuffet#38]
An issue where the farming station would, about 90 percent of the time, remove the seed and matured product from the Magical Crops mod. Research dictated that in the Magical Crops cfg, there is an option to auto-replant, turning it off will fix this issue. 

Also, i placed cotton within the farming station. It planted normally, but once it grew to maturity, the station would TRY to harvest it, leaving the cotton and its seeds on the ground and not in the stations inventory.

**Comment by topher2010** [comment]
auto-replant has been disabled in 3.0.1
