### ISSUE TITLE
Mod Suggestion

### ISSUE THREAD

**Issue by Xenosaga20** [BreakfastCraft/BreakfastBuffet#4]
Hey topher here's another mod suggestion LanteaCraft which is a stargate mod here's the link to the page for more info http://lanteacraft.com/ It works with computer craft ic2 and thermal expansion. LanteaCraft is based off the original SGCraft by greg.ewing. Also it is updated to 1.7.10

**Comment by topher2010** [comment]
Unfortunately it appears it only adds portals, which is kind of redundant at this time.  I won't be adding it into the pack in the near future.
