### ISSUE TITLE
change compact machine biomes.

### ISSUE THREAD

**Issue by demethan** [BreakfastCraft/BreakfastBuffet#43]
steam engine from Rotary Craft don't work in Compact Machines. This is the explaination I got from the forum

----------------------------

Demethan, you needa check the biome in the compact machine, it's the sky (End) biome meaning that it is very cold about -100C if i remember right. Basically said it is all working normally, and you can fix this in the configs of Compact Machines, the option of using the biome of the area the machine was placed in.

**Comment by topher2010** [comment]
this is a non-issue, Reika has heaters in his mods.
