### ISSUE TITLE
Pam's water crops are unplantable

### ISSUE THREAD

**Issue by Dahbaron** [BreakfastCraft/BreakfastBuffet#44]
https://github.com/MatrexsVigil/harvestcraft/issues/14

**Comment by topher2010** [comment]
Seems there isn't currently a fix or workaround for this.  I will keep an eye out for either.

**Comment by F4ndroid** [comment]
In the meantime use ZTones Garden Soil to grow them.

**Comment by demethan** [comment]
Need update.  This is fixed. 

https://github.com/MatrexsVigil/harvestcraft/pull/18

**Comment by topher2010** [comment]
THis is updated in the next version.
