### ISSUE TITLE
Rotarycraft / AOBD Interaction Bug

### ISSUE THREAD

**Issue by waerloga** [BreakfastCraft/BreakfastBuffet#46]
Rotarycraft Extractor does not process ores beyond itself and vanilla. as referenced in https://github.com/ganymedes01/Another-One-Bites-the-Dust/issues/72.

The current fix is to find/replace rotarycraft = true to rotarycraft = false in aobd.cfg

**Comment by topher2010** [comment]
This has been done and will be in BB3.0.2
