### ISSUE TITLE
Minechem machine buffers

### ISSUE THREAD

**Issue by F4ndroid** [BreakfastCraft/BreakfastBuffet#48]
There are Minechem recipes that do not work because the default value is too small. After asking on the Minechem IRC channel I was told that the buffer needs to be increased to handle these recipes. They recommended 10000000RF.

Change all of these values to 10000000 to fix.

    # Max power that the decomposer can hold
    I:maxDecomposerStorage=10000

    # Max power that the fission reactor can hold
    I:maxFissionStorage=100000

    # Max power that the fusion reactor can hold
    I:maxFusionStorage=100000

    # Max power that the synthesizer can hold
    I:maxSynthesizerStorage=100000

**Comment by topher2010** [comment]
will be changed in BB3.0.2
