### ISSUE TITLE
Witchery villager in mob grinder is preventing client connection.

### ISSUE THREAD

**Issue by demethan** [BreakfastCraft/BreakfastBuffet#49]
Either we update Witchery or remove it.

**Comment by waerloga** [comment]
Specifically it's witchery mob + extra utilities spike. It does not seem specific to 

Additionally referenced:
https://github.com/RTRGitHub/RTRRedux/issues/166
https://github.com/brandon3055/Draconic-Evolution/issues/72

**Comment by waerloga** [comment]
We have a problem. It's any villager.

**Comment by waerloga** [comment]
Solution:
1: remove witchery
2: policy of no fakeplayers killing any villager. (not that they drop anything from what I recall)

**Comment by demethan** [comment]
that was an unexperienced player error.  I think the policy will be fine.

**Comment by F4ndroid** [comment]
Consider adding the rule to the sign at spawn.

**Comment by demethan** [comment]
Can we disable the villagers from witchcraft.  Mod hasn`t updated since April and seems abandoned.

**Comment by demethan** [comment]
posted a topic in irc for warning.. no one should make a villager grinder. its just not useful
