### ISSUE TITLE
Minechem causing incorrect enchantments

### ISSUE THREAD

**Issue by F4ndroid** [BreakfastCraft/BreakfastBuffet#50]
Using the Advanced Enchantment Table and attempting to apply Soulbound fails. Using the Ender IO enchanter results in an Asparagine Coated enchantment.
Thus, the simplest route is to disable Minechem enchants.

    # Enable chemical weapon effects
    B:swordEffects=true

Set this to false and we should be good.

**Comment by demethan** [comment]
Topher, Minechem are not really needed .. I Approve, your call.

**Comment by topher2010** [comment]
Will be so in the next update
