### ISSUE TITLE
Mods suggestions :D 

### ISSUE THREAD

**Issue by shobu9** [BreakfastCraft/BreakfastBuffet#51]
Armourer's workshop: http://minecraft.curseforge.com/mc-mods/229523-armourers-workshop/files

Matter Overdrive : http://minecraft.curseforge.com/mc-mods/229694-matter-overdrive

Chromaticraft --- to donut

Jewelrycraft 2 : http://www.curse.com/mc-mods/minecraft/229927-jewelrycraft-2

**Comment by demethan** [comment]
NO- Alpha

NO - too op

NO - too anoying

Maybe  - Next run. contains Ore gen.
