### ISSUE TITLE
New Mod suggestion

### ISSUE THREAD

**Issue by Xenosaga20** [BreakfastCraft/BreakfastBuffet#54]
Here's a link to the mod page would be nice to have this for a quarry world instead of having to make one with the rftools and what not.

http://www.curse.com/mc-mods/minecraft/aroma1997s-dimensional-world

**Comment by demethan** [comment]
ya.. We tried that mod many time.. It is very buggy for MP.  Never worked properly. 

Thanks for your suggestion.
