### ISSUE TITLE
Magical Crops recipe tweak

### ISSUE THREAD

**Issue by demethan** [BreakfastCraft/BreakfastBuffet#56]
![enderiumseeds](https://cloud.githubusercontent.com/assets/5810363/11049916/d2e5b0fa-870f-11e5-8649-d6e770c443f3.PNG)
enderiumBlock, ZivicioBlock, enderiumBlock,
 ZivicioBlock,endermanSeed, ZivicioBlock
enderiumBlock, ZivicioBlock, enderiumBlock,  = enderiumSeed

![endermanseeds](https://cloud.githubusercontent.com/assets/5810363/11049917/d2e806de-870f-11e5-863f-2d5b413a76be.PNG)

EndermanHead,Zivicio,EndermanHead
zivicio, diamondSeed, zivicio
EndermanHead,Zivicio,EndermanHead = enderManSeed

**Comment by topher2010** [comment]
This will be in the next update.
