### ISSUE TITLE
bug magical crops sheep essence not creating usable wool

### ISSUE THREAD

**Issue by nota141** [BreakfastCraft/BreakfastBuffet#59]
as per https://mineyourmind.net/forum/threads/bug-magical-crops-sheep-essence.9484/

not an issue that does not have a work around (cotton -> string -> wool) but still an issue.

**Comment by slidingmike** [comment]
This requires a MTRM recipe to be created.

**Comment by slidingmike** [comment]
Possibly fixed with 3.1.0 Update, Please confirm after update is released.

**Comment by demethan** [comment]
Not fixed.  need to report to mod auther.

**Comment by demethan** [comment]
fixed with minetweaker.
