### ISSUE TITLE
Recipe conflict

### ISSUE THREAD

**Issue by UnNinja** [BreakfastCraft/BreakfastBuffet#63]
Extra utilities blackout curtains and the malius doors curtain both share the same recipe (a 2x3 of wool)

**Comment by slidingmike** [comment]
This will need a MTRM recipe to be created.

**Comment by demethan** [comment]
there is a mod to fix this stuff. see issue #70

**Comment by demethan** [comment]
you need to use at least one colored wool to get the curtains
