### ISSUE TITLE
Compact Machines config

### ISSUE THREAD

**Issue by F4ndroid** [BreakfastCraft/BreakfastBuffet#67]
Some quality of life things to consider for Compact Machines.

Allows us to use Warp Pages to move between machines without having to carry a PSD:

    B:allowEnterWithoutPSD=true

Allows Botania integration:

    B:Botania=true

**Comment by slidingmike** [comment]
Top half denied by Topher, Bottom Half has been corrected. Please close (3.1.0 Update)

**Comment by demethan** [comment]
Minor tweaks.. I don`t mind.

**Comment by slidingmike** [comment]
I'm not against these either on the thought that Warp Books stays in.

**Comment by demethan** [comment]
Botania  implemented 

Still need PSD ( Topher's rule)
