### ISSUE TITLE
Updates

### ISSUE THREAD

**Issue by UnNinja** [BreakfastCraft/BreakfastBuffet#68]
http://pastebin.com/qtw1bvRY

**Comment by UnNinja** [comment]
Magical crops also has a new public beta version, but it splits it into 3 separate mods;
[Core](http://www.curse.com/mc-mods/minecraft/232150-magical-crops-core), [Armoury](http://www.curse.com/mc-mods/minecraft/232149-magical-crops-armoury), and  [Decorative](http://www.curse.com/mc-mods/minecraft/232182-magical-crops-decorative).

**Comment by UnNinja** [comment]
[Chisel](http://minecraft.curseforge.com/projects/chisel) is apparently being updated in a new fork

**Comment by UnNinja** [comment]
[Reika's various mods](https://sites.google.com/site/reikasminecraft/latest-downloads)

**Comment by slidingmike** [comment]
Fixed in 3.1.0 Please Close
