### ISSUE TITLE
Suggestion: Add Agricraft!

### ISSUE THREAD

**Issue by lunaKM** [BreakfastCraft/BreakfastBuffet#69]
It would help immensely since Spice of Life is installed to boost crop production, allow mutation of species and higher yields.

**Comment by demethan** [comment]
I second this motion.

**Comment by Lunchington** [comment]
its my favorite mod so yes plz

**Comment by slidingmike** [comment]
https://github.com/BreakfastCraft/BreakfastBuffet/issues/71
