### ISSUE TITLE
Suggestion: Make Magical Crops Harder

### ISSUE THREAD

**Issue by Winrylive** [BreakfastCraft/BreakfastBuffet#71]
If we add Agricraft, and it's looking like it's a possibility, then we should make magical crops harder recipes or not allow them to be mutatable using Agricraft. I feel it would be far to cheaty OP to have magical crops be that easy.

**Comment by slidingmike** [comment]
Most likely Magical Crops would not be added. Agricraft would be the replacement.

We are exploring this with Lunchington right now.

**Comment by Winrylive** [comment]
Ah removing Magical Crops is a solution too :P

**Comment by slidingmike** [comment]
I think a mutual opinion right now is the level of interaction required for agricraft is much more balanced than that of magical crops. However as always, more thoughts/opinions will go into this as we move in development.
