### ISSUE TITLE
Named/Jailed Mobs despawn after server restart

### ISSUE THREAD

**Issue by Winrylive** [BreakfastCraft/BreakfastBuffet#72]
I'd have to look up my stream archive to find the 2 streams I mentioned this, but I used jailer safari nets on witches for my blood altar and when I came back after a server restart they had despawned. This also happened to a nametagged witch I tried first.

**Comment by slidingmike** [comment]
What was it you used on Juice that despawned? A name tag?

**Comment by Winrylive** [comment]
Yes it was a nametag on a Blaze.

**Comment by slidingmike** [comment]
@demethan Any ideas?

**Comment by demethan** [comment]
I had the same problem on Bacon with a jailled squid. No idea!!!
