### ISSUE TITLE
NEI Recipe for Sand = Crash

### ISSUE THREAD

**Issue by slidingmike** [BreakfastCraft/BreakfastBuffet#79]
I'm guessing a recipe for sand is placed by the mods that is causing a CTD for the pack. Need research on mods that do recipes for sand as well as research for possible fix.

Duplicated by several:

Slidingmike
FMA_Winry
schr

**Comment by slidingmike** [comment]
https://mineyourmind.net/forum/threads/crash-bug-on-nei-sand-recipe-lookup.12146/

Shows NEIAddons as a possible culprit/fix

**Comment by demethan** [comment]
fixed
