### ISSUE TITLE
Delays on teleportation commands

### ISSUE THREAD

**Issue by NiSiSuinegEht** [BreakfastCraft/BreakfastBuffet#84]
/home, /spawn, and /back all still have the default 5 second delay.  As this has been removed on other packs in the past, could that be done with this one as well?

**Comment by demethan** [comment]
`ftbutilities.homes.warmup: 0     `

`ftbutilities.homes.cooldown: 0     `

`ftbutilities.back.cooldown: 0    ` 

`ftbutilities.warp.cooldown: 0     `


config applied
