### ISSUE TITLE
Akashic Tome Config

### ISSUE THREAD

**Issue by OfMCMXXXVII** [BreakfastCraft/BreakfastBuffet#87]
A couple of the guides are not able to craft into it.  Request to add TOP's readme, Compact Machine's PSD, and Cylic's trading almanac into the whitelist

Their IDs respectively are "theoneprobe:probenote, compactmachines3:psd, and cyclicmagic:tool_trade"

Also possibly the addition of "minecraft:written_book"

**Comment by demethan** [comment]
done
