### ISSUE TITLE
When creating a new singleplayer world the game crashes

### ISSUE THREAD

**Issue by Bulluk** [BreakfastCraft/BreakfastBuffet#94]
see report: https://pastebin.com/dGi761hn.

It has to do something RFTools dimensions. 
I did some Googling on the error code but I couldn't find anything concrete.

I suppose it's not a big of a deal since we are using this pack on the server, which doesn't crash. Probably because of VanillaFix. But it might bring issues in the future so it might be a good idea to take a look at it.

**Comment by demethan** [comment]
works fine on my instance.
