### ISSUE TITLE
Request: Disable Endermites from Nether/End Ores

### ISSUE THREAD

**Issue by Bulluk** [BreakfastCraft/BreakfastBuffet#95]
It would seem there's a second mod which adds this feature, and that is Cyclic
Requesting to have this disabled aswell.

As it's only needed to change server-side this can be done without clients needing to update this pack, so that's nice.

Config file: config/cyclicmagic.cfg
Line: 916
Change: _B:"Infested Ores"=true_ to _B:"Infested Ores"=false_

**Comment by demethan** [comment]
will be in 1.5.3
