### ISSUE TITLE
Applied Energistics 2 & Wireless Crafting Terminal 2 - not same version

### ISSUE THREAD

**Issue by Bulluk** [BreakfastCraft/BreakfastBuffet#96]
These 2 mods work best together when they are the same version. 

The Applied Energistics 2 mod in the Buffet pack is on version RV6-stable1 or simply on the RV6 version.
The Wireless Crafting Terminal 2 mod in the Buffet pack is on version 3.9.68, which is for AE2 RV5.

Please change the WCT2 version to WirelessCraftingTerminal-1.12.2-3.10.81.jar (RV6)
Link: https://minecraft.curseforge.com/projects/wireless-crafting-terminal/files/2618508

On the Curseforge page for WCT2 there are 2 versions you can download, for RV5 and RV6.

The AE2 and WCT2 versions must be the same cause instabilities happen when they mismatch.

Currently I'm experiencing an issue where the WCT cannot deposit or withdrawel items from the ME system. Which completely makes the device useless.

Reference: https://github.com/p455w0rd/WirelessCraftingTerminal/issues/297

**Comment by demethan** [comment]
will be in 1.5.3
